# -*- coding: utf-8 -*-
"""OutletIQ_Utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvEwJ77toMdAKR3FUc_lmwgTmp6Tr0iv
"""

def calculate_radar_values(outlet):
    """
    Calculate normalized values for the radar chart based on outlet metrics.

    Args:
        outlet: The outlet data dictionary/series

    Returns:
        A list of normalized values for the radar chart
    """
    # These values are already normalized in the mock data
    radar_values = [
        outlet["review_rating"],
        outlet["demographics_score"],
        outlet["opportunity_score"],
        outlet["value_profile"],
        outlet["menu_category_focus"]
    ]

    return radar_values