# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCl_r2rdVjmrH3nY9VOAGttyOzX4eTOh
"""

import streamlit as st

st.title("Hello, Streamlit! 👋")
st.write("This is my first Streamlit app.")